[tool.poetry]
name = "spacetrader"
version = "0.1.0"
description = ""
authors = ["AntoniaLivia79 <antoniablanchflower@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.09"
bcrypt = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"